//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.27 at 09:36:13 PM BST 
//


package testdomain.music;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DigitalAlbum complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DigitalAlbum">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.grizzlytech.org/testdomain/music}Album">
 *       &lt;sequence>
 *         &lt;element name="bitRate" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DigitalAlbum", propOrder = {
    "bitRate"
})
public class DigitalAlbum
    extends Album
{

    protected int bitRate;

    /**
     * Gets the value of the bitRate property.
     * 
     */
    public int getBitRate() {
        return bitRate;
    }

    /**
     * Sets the value of the bitRate property.
     * 
     */
    public void setBitRate(int value) {
        this.bitRate = value;
    }

}
