//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.27 at 09:36:13 PM BST 
//


package testdomain.music;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the testdomain.music package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CD_QNAME = new QName("http://www.grizzlytech.org/testdomain/music", "CD");
    private final static QName _Digital_QNAME = new QName("http://www.grizzlytech.org/testdomain/music", "digital");
    private final static QName _Library_QNAME = new QName("http://www.grizzlytech.org/testdomain/music", "library");
    private final static QName _Vinyl_QNAME = new QName("http://www.grizzlytech.org/testdomain/music", "vinyl");
    private final static QName _Format_QNAME = new QName("http://www.grizzlytech.org/testdomain/music", "format");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: testdomain.music
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DigitalAlbum }
     * 
     */
    public DigitalAlbum createDigitalAlbum() {
        return new DigitalAlbum();
    }

    /**
     * Create an instance of {@link Album }
     * 
     */
    public Album createAlbum() {
        return new Album();
    }

    /**
     * Create an instance of {@link Library }
     * 
     */
    public Library createLibrary() {
        return new Library();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Album }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.grizzlytech.org/testdomain/music", name = "CD", substitutionHeadNamespace = "http://www.grizzlytech.org/testdomain/music", substitutionHeadName = "format")
    public JAXBElement<Album> createCD(Album value) {
        return new JAXBElement<Album>(_CD_QNAME, Album.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DigitalAlbum }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.grizzlytech.org/testdomain/music", name = "digital", substitutionHeadNamespace = "http://www.grizzlytech.org/testdomain/music", substitutionHeadName = "format")
    public JAXBElement<DigitalAlbum> createDigital(DigitalAlbum value) {
        return new JAXBElement<DigitalAlbum>(_Digital_QNAME, DigitalAlbum.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Library }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.grizzlytech.org/testdomain/music", name = "library")
    public JAXBElement<Library> createLibrary(Library value) {
        return new JAXBElement<Library>(_Library_QNAME, Library.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Album }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.grizzlytech.org/testdomain/music", name = "vinyl", substitutionHeadNamespace = "http://www.grizzlytech.org/testdomain/music", substitutionHeadName = "format")
    public JAXBElement<Album> createVinyl(Album value) {
        return new JAXBElement<Album>(_Vinyl_QNAME, Album.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.grizzlytech.org/testdomain/music", name = "format")
    public JAXBElement<Object> createFormat(Object value) {
        return new JAXBElement<Object>(_Format_QNAME, Object.class, null, value);
    }

}
