//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.22 at 02:41:06 PM BST 
//


package testdomain.zoo;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the testdomain.zoo package. 
 * <p>An AbstractObjectFactory allows you to programatically
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Zoo_QNAME = new QName("http://www.grizzlytech.org/testdomain/zoo", "zoo");

    /**
     * Create a new AbstractObjectFactory that can be used to create new instances of schema derived classes for package: testdomain.zoo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Zoo }
     * 
     */
    public Zoo createZoo() {
        return new Zoo();
    }

    /**
     * Create an instance of {@link Dolphin }
     * 
     */
    public Dolphin createDolphin() {
        return new Dolphin();
    }

    /**
     * Create an instance of {@link Penguin }
     * 
     */
    public Penguin createPenguin() {
        return new Penguin();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Zoo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.grizzlytech.org/testdomain/zoo", name = "zoo")
    public JAXBElement<Zoo> createZoo(Zoo value) {
        return new JAXBElement<Zoo>(_Zoo_QNAME, Zoo.class, null, value);
    }

}
