//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.22 at 02:41:06 PM BST 
//


package testdomain.zoo;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for penguin complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="penguin">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.grizzlytech.org/testdomain/zoo}animal">
 *       &lt;sequence>
 *         &lt;element name="fishPerDay" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "penguin", propOrder = {
    "fishPerDay"
})
public class Penguin
    extends Animal
{

    protected BigInteger fishPerDay;

    /**
     * Gets the value of the fishPerDay property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFishPerDay() {
        return fishPerDay;
    }

    /**
     * Sets the value of the fishPerDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFishPerDay(BigInteger value) {
        this.fishPerDay = value;
    }

}
